### PR TITLE
QUIC client fuzzer corpora files

### PR DESCRIPTION
**Pull request by mattcaswell**
Corpora files for the new quic-client fuzzer.

### CODE REVIEW

**Comment by mattcaswell** [comment]
See openssl/openssl#22368 for the fuzzer that uses these files.

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
ping for second review

**Comment by kroeckx** [comment]
I intend to update my PR, with more coverage using less files than this PR.

**Review by hlandau — APPROVED** [review]

**Comment by kroeckx** [comment]
So I've updated #13. I suggest we use that corpus instead. It has a much larger coverage.

**Comment by mattcaswell** [comment]
Closing in favour of #13...please approve that one!

**Pull request closed without merging**
