### PR TITLE
Add quic-client corpus

### PR DESCRIPTION
**Pull request by kroeckx**
This is an initial version that doesn't have that much coverage yet. It seems to be stuck getting new coverage, and someone will need to look on how to make it cover more code.

### CODE REVIEW

**Review by paulidale — APPROVED** [review]

**Comment by kroeckx** [comment]
I wasn't really looking to merge this yet, and don't see an option to convert this to a draft. It was mainly here so people that want to look at it already have some files. But I wouldn't mind this being merged either.

**Comment by paulidale** [comment]
Convert to draft is top right under reviewers.
Completely different place to the ready for review button :disappointed:

**Review by mattcaswell — APPROVED** [review]

**Comment by mattcaswell** [comment]
Ping for reviews!

**Review by hlandau — APPROVED** [review]

**Comment by t8m** [comment]
The format has been changed with the recent quic client fuzzer. This needs an update.

**Comment by kroeckx** [comment]
I'll update it tonight

**Review by mattcaswell — APPROVED** [review]

**Review by levitte — APPROVED** [review]

**Comment by mattcaswell** [comment]
Pushed. Thanks.

**Pull request closed without merging**
