### PR TITLE
Adds dtls corpora

### PR DESCRIPTION
**Pull request by fwh-dc**

### CODE REVIEW

**Comment by kroeckx** [comment]
Since this started from the tls corpus, it's likely that this doesn't actually give good coverage. Is it possible to generate example files, for instance hacking up s_client to dump everything send and received to a file, and add that to the corpus and let it run for a while? Note that you want to do that with an s_client and s_server build with the same options as the fuzzer.

Could you try to minimize the corpus?

**Comment by fwh-dc** [comment]
Sure, that should be possible. 
Should I run the s_client and s_server a couple of times with varying setup i.e. cipherlists, dtls versions?
And I assume that encryption should be turned off? Or how does that work for the tls tests?
How much is a "while"? 5mins, 20mins, 2hours?

**Comment by kroeckx** [comment]
Having 1 file for client and server is fine, but more examples are always better. This is all about making it easier for the fuzzer to find coverage, otherwise it can take a long time before it actually starts finding interesting things.

In the fuzzer you set ALL:eNULL:@SECLEVEL=0 as cipherstring, you want to give s_client and s_server the same string.

Having it run for 20 minutes is more than enough.

**Comment by fwh-dc** [comment]
Ok I did an update to the corpora. Here's the procedure I followed, please let me know if there is more to be done:

Here's the build config:
```
LDFLAGS="-L/usr/local/opt/llvm@15/lib  -Wl,-rpath,/usr/local/opt/llvm@15/lib" ../config enable-fuzz-libfuzzer \
        --with-fuzzer-lib=/usr/local/Cellar/llvm@15/15.0.7/lib/clang/15.0.7/lib/darwin/libclang_rt.fuzzer_osx.a \
        -DPEDANTIC -fsanitize=fuzzer-no-link enable-ubsan enable-asan no-shared \
        -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION \
        enable-ec_nistp_64_gcc_128 -fno-sanitize=alignment \
        enable-weak-ssl-ciphers enable-rc5 enable-md2 \
        enable-ssl3 enable-ssl3-method enable-nextprotoneg \
        --debug -lc++
```

Add the following to dtls_read_bytes

```
    char *filename = sc->server ? "serverinput.bin" : "clientinput.bin";
    FILE *ptr = fopen(filename, "a");
    if (ossl_assert(ptr != NULL)) {
        fwrite(rr->data, 1, rr->length, ptr);
        fclose(ptr);
    }
```

Now the records will be written to serverinput.bin or clientinput.bin and these
can be used as initial corpus for the dtlsserver and dtlsclient.

Then we do a couple of handshakes using the s_server and s_client with different
settings. Needs to be done for each server private key/cert pair supported by
the fuzzer.

First run

```
./util/shlib_wrap.sh ./apps/openssl s_server -cert rsa_srv.crt \
                                             -key rsa_srv.key \
                                             -cipher ALL:eNULL:@SECLEVEL=0 \
                                             -dtls
./util/shlib_wrap.sh ./apps/openssl s_client -cipher ALL:eNULL:@SECLEVEL=0 \
                                             -dtls
mv serverinput.bin server1.bin
mv clientinput.bin client1.bin
```

Second run

```
./util/shlib_wrap.sh ./apps/openssl s_server -cert rsa_srv.crt \
                                             -key rsa_srv.key \
                                             -cipher ALL:eNULL:@SECLEVEL=0 \
                                             -dtls
./util/shlib_wrap.sh ./apps/openssl s_client -cipher ALL:eNULL:@SECLEVEL=0 \
                                             -dtls1
mv serverinput.bin server2.bin
mv clientinput.bin client2.bin
```

Third run

```
./util/shlib_wrap.sh ./apps/openssl s_server -cert rsa_srv.crt \
                                             -key rsa_srv.key \
                                             -cipher ALL:eNULL:@SECLEVEL=0 \
                                             -dtls
./util/shlib_wrap.sh ./apps/openssl s_client -cipher ALL:eNULL:@SECLEVEL=0 \
                                             -dtls1_2
mv serverinput.bin server3.bin
mv clientinput.bin client3.bin
```

Fourth run

```
./util/shlib_wrap.sh ./apps/openssl s_server -cert rsa_srv.crt \
                                             -key rsa_srv.key \
                                             -cipher ALL:eNULL:@SECLEVEL=0 \
                                             -dtls1
./util/shlib_wrap.sh ./apps/openssl s_client -cipher ALL:eNULL:@SECLEVEL=0 \
                                             -dtls
mv serverinput.bin server4.bin
mv clientinput.bin client4.bin
```

Fifth run

```
./util/shlib_wrap.sh ./apps/openssl s_server -cert rsa_srv.crt \
                                             -key rsa_srv.key \
                                             -cipher ALL:eNULL:@SECLEVEL=0 \
                                             -dtls1_2
./util/shlib_wrap.sh ./apps/openssl s_client -cipher ALL:eNULL:@SECLEVEL=0 \
                                             -dtls
mv serverinput.bin server5.bin
mv clientinput.bin client5.bin
```

Sixth run

```
./util/shlib_wrap.sh ./apps/openssl s_server -cert ecdsa_srv.crt \
                                             -key ecdsa_srv.key \
                                             -cipher ALL:eNULL:@SECLEVEL=0 \
                                             -dtls
./util/shlib_wrap.sh ./apps/openssl s_client -cipher ALL:eNULL:@SECLEVEL=0 \
                                             -dtls
mv serverinput.bin server6.bin
mv clientinput.bin client6.bin
```

Seventh run

```
./util/shlib_wrap.sh ./apps/openssl s_server -cert ecdsa_srv.crt \
                                             -key ecdsa_srv.key \
                                             -cipher ALL:eNULL:@SECLEVEL=0 \
                                             -dtls
./util/shlib_wrap.sh ./apps/openssl s_client -cipher ALL:eNULL:@SECLEVEL=0 \
                                             -dtls1
mv serverinput.bin server7.bin
mv clientinput.bin client7.bin
```

Eight run

```
./util/shlib_wrap.sh ./apps/openssl s_server -cert ecdsa_srv.crt \
                                             -key ecdsa_srv.key \
                                             -cipher ALL:eNULL:@SECLEVEL=0 \
                                             -dtls
./util/shlib_wrap.sh ./apps/openssl s_client -cipher ALL:eNULL:@SECLEVEL=0 \
                                             -dtls1_2
mv serverinput.bin server8.bin
mv clientinput.bin client8.bin
```

Ninth run

```
./util/shlib_wrap.sh ./apps/openssl s_server -cert ecdsa_srv.crt \
                                             -key ecdsa_srv.key \
                                             -cipher ALL:eNULL:@SECLEVEL=0 \
                                             -dtls1
./util/shlib_wrap.sh ./apps/openssl s_client -cipher ALL:eNULL:@SECLEVEL=0 \
                                             -dtls
mv serverinput.bin server9.bin
mv clientinput.bin client9.bin
```

Tenth run

```
./util/shlib_wrap.sh ./apps/openssl s_server -cert ecdsa_srv.crt \
                                             -key ecdsa_srv.key \
                                             -cipher ALL:eNULL:@SECLEVEL=0 \
                                             -dtls1_2
./util/shlib_wrap.sh ./apps/openssl s_client -cipher ALL:eNULL:@SECLEVEL=0 \
                                             -dtls
mv serverinput.bin server10.bin
mv clientinput.bin client10.bin
```

Eleventh run

```
./util/shlib_wrap.sh ./apps/openssl s_server -cert dsa_srv.crt \
                                             -key dsa_srv.key \
                                             -cipher ALL:eNULL:@SECLEVEL=0 \
                                             -dtls
./util/shlib_wrap.sh ./apps/openssl s_client -cipher ALL:eNULL:@SECLEVEL=0 \
                                             -dtls
mv serverinput.bin server11.bin
mv clientinput.bin client11.bin
```

Twelve run

```
./util/shlib_wrap.sh ./apps/openssl s_server -cert dsa_srv.crt \
                                             -key dsa_srv.key \
                                             -cipher ALL:eNULL:@SECLEVEL=0 \
                                             -dtls
./util/shlib_wrap.sh ./apps/openssl s_client -cipher ALL:eNULL:@SECLEVEL=0 \
                                             -dtls1
mv serverinput.bin server12.bin
mv clientinput.bin client12.bin
```

Thirteenth run

```
./util/shlib_wrap.sh ./apps/openssl s_server -cert dsa_srv.crt \
                                             -key dsa_srv.key \
                                             -cipher ALL:eNULL:@SECLEVEL=0 \
                                             -dtls
./util/shlib_wrap.sh ./apps/openssl s_client -cipher ALL:eNULL:@SECLEVEL=0 \
                                             -dtls1_2
mv serverinput.bin server13.bin
mv clientinput.bin client13.bin
```

Fourteenth run

```
./util/shlib_wrap.sh ./apps/openssl s_server -cert dsa_srv.crt \
                                             -key dsa_srv.key \
                                             -cipher ALL:eNULL:@SECLEVEL=0 \
                                             -dtls1
./util/shlib_wrap.sh ./apps/openssl s_client -cipher ALL:eNULL:@SECLEVEL=0 \
                                             -dtls
mv serverinput.bin server14.bin
mv clientinput.bin client14.bin
```

Fifteenth run

```
./util/shlib_wrap.sh ./apps/openssl s_server -cert dsa_srv.crt \
                                             -key dsa_srv.key \
                                             -cipher ALL:eNULL:@SECLEVEL=0 \
                                             -dtls1_2
./util/shlib_wrap.sh ./apps/openssl s_client -cipher ALL:eNULL:@SECLEVEL=0 \
                                             -dtls
mv serverinput.bin server15.bin
mv clientinput.bin client15.bin
```

Move all the corpora to `fuzz/corpora/dtlsserverinit/` and `fuzz/corpora/dtlsclientinit/`.

Run
```
./fuzz/dtlsserver ../fuzz/corpora/dtlsserverinit/
./fuzz/dtlsclient ../fuzz/corpora/dtlsclientinit/

./fuzz/dtlsclient -merge=1 ../fuzz/corpora/dtlsclient ../fuzz/corpora/dtlsclientinit
./fuzz/dtlsserver -merge=1 ../fuzz/corpora/dtlsserver ../fuzz/corpora/dtlsserverinit
```

**Comment by kroeckx** [comment]
That looks good

**Review by kroeckx — APPROVED** [review]

**Comment by fwh-dc** [comment]
@t8m
Should I update the related pr in the openssl repo with this corpora branch? Or should this be accepted and then I update the related pr?

**Review by mattcaswell — APPROVED** [review]

**Comment by mattcaswell** [comment]
Pushed.

@fwh-dc - you should be able to update the related PR now.

**Pull request closed without merging**
