### PR TITLE
Add provider fuzzer corpus

### PR DESCRIPTION
**Pull request by maxammann**
Adds the provider corpus for https://github.com/openssl/openssl/pull/22964

### CODE REVIEW

**Comment by maxammann** [comment]
Hm it is rather a lot of files. Not sure if I should try to minimize this first

**Comment by t8m** [comment]
> Hm it is rather a lot of files. Not sure if I should try to minimize this first

Yes please, if possible.

**Comment by maxammann** [comment]
Minimized to around 800 files.

**Comment by t8m** [comment]
> Minimized to around 800 files.

Much better!

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
Merged. Thank you for your contribution.

Now you can update the submodule in your openssl/openssl PR.

**Pull request closed without merging**
