### PR TITLE
Add a conf testcase causing a timeout (3.1/3.0)

### PR DESCRIPTION
**Pull request by mattcaswell**
This is a testcase from ossfuzz causing a timeout in the conf fuzzer. See openssl/openssl#20839 for the resolution.

This is a backport of #6 to the 3.1/3.0 branches. I realised this needs to go there too, because the timeout was experienced in those branches.

### CODE REVIEW

**Review by paulidale — APPROVED** [review]

**Comment by mattcaswell** [comment]
Given the recent OTC decision can I just merge this now?

**Comment by kroeckx** [comment]
I currently don't see the need to have branches for the corpora

**Comment by t8m** [comment]
> I currently don't see the need to have branches for the corpora

Yeah, we did not really decide what to do with the fuzz corpora on 3.1 and 3.0 branches in the main repo. I assume if we just remove the corpora there and use the main branch commit with the submodule and the tests pass, we should be OK.

**Comment by paulidale** [comment]
I'd much prefer to not have branched corpora too.

**Comment by mattcaswell** [comment]
Ok. Closing this. I raised a question about the 3.1/3.0 corpora in openssl/openssl#20903

**Pull request closed without merging**
