### PR TITLE
Update asn1 corpus

### PR DESCRIPTION
**Pull request by kroeckx**
Replaces #1

### CODE REVIEW

**Review by t8m — APPROVED** [review]

**Comment by tom-cosgrove-arm** [comment]
@t8m Any suggestions as to how to go about a review of this?

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
Unfortunately, I don't think this can be meaningfully reviewed in detail.

**Comment by kroeckx** [comment]
I can generate some stats if that's useful

**Comment by paulidale** [comment]
I don't think it's required.
Even with such, it would still be a non-detailed review.

**Comment by kroeckx** [comment]
So is this ready to get merged? Or do we still need to check/fix some automation?

Is there some automation for creating a pull request in the main repository after this has been merged?

**Comment by paulidale** [comment]
I've merged this.

There is no automation to do what you want.  There should be I think.

**Comment by levitte** [comment]
I raise issue #3 and #4 to discuss the questions raised here

**Pull request closed without merging**
