### PR TITLE
Update asn1 corpora

### PR DESCRIPTION
**Pull request by levitte**
This is a transfer of openssl/openssl#19669

### CODE REVIEW

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
Ha, the reviewers aren't setup correctly on the repo.

**Comment by t8m** [comment]
It should have same permissions as the main source repo.

**Comment by levitte** [comment]
I'll fix that

**Comment by levitte** [comment]
Fixed up

**Comment by kroeckx** [comment]
Since this is an old corpus, I would actually like to create a new one already.

**Pull request closed without merging**
