### PR TITLE
Add attribute certificate corpus

### PR DESCRIPTION
**Pull request by dhobsong**
Corpus for attribute certificate fuzz testing.
Attribute certificate support added in PR: https://github.com/openssl/openssl/pull/15857

### CODE REVIEW

**Comment by dhobsong** [comment]
@JonathanWilbur This corpus is seeded in part with the test attribute certificate that you provided [here](https://github.com/openssl/openssl/pull/15857#issuecomment-1610368056).  I'd like to add your <Acked-by> or other to this commit message.  Please let me know if that's ok.

**Comment by JonathanWilbur** [comment]
I am not quite sure what you are asking, but if you are asking to include the attribute certificate I produced in that thread, you are absolutely welcome to. I grant you unlimited license to it, and I would be happy to produce more for you if you'd like. Please let me know if I can do anything else to help.

**Comment by dhobsong** [comment]
Thanks. I was asking to add your name to the commit message in the form of 

Acked-by: Jonathan M. Wilbur \<jonathan@wilbur.space\>
(Sorry I used angle brackets in my previous comment, hiding the most important part)

so that your permission will be captured in the git log, instead of just the PR comments.

**Comment by JonathanWilbur** [comment]
I created a PR to include such a commit: https://github.com/dhobsong/fuzz-corpora/pull/1

**Comment by JonathanWilbur** [comment]
image

**Comment by dhobsong** [comment]
Thanks. I've added your "Ack" to the commit in this PR.

**Review by t8m — APPROVED** [review]

**Comment by dhobsong** [comment]
Sorry.  It looks like I closed this somehow by accident?!   Reopening

**Comment by t8m** [comment]
Merged to the main branch. Thank you for your contribution.

**Pull request closed without merging**
